### ISSUE TITLE
Multithreaded

### ISSUE THREAD

**Issue by bufordtaylor** [thbar/kiba#19]
Currently a kiba job takes hours. It would be nice to reduce that with threading.

**Comment by thbar** [comment]
Hello @bufordtaylor!

As announced [on my blog here](http://thibautbarrere.com/2015/06/04/what-s-ahead-for-kiba-etl/#kiba-pro-on-steroids-yearly-subscription), multi-threading is planned in the upcoming Kiba Pro offering.

I could even go as far as to develop a multi-machines version at some point.

You can [read more about Kiba Pro here](https://github.com/thbar/kiba/issues/20), where I outlined the potential feature set and subscription.

Do you think your company could be interested?

I would love to hear your thoughts on this, either here of [via email](mailto:thibaut.barrere@gmail.com).

Thanks!

**Comment by thbar** [comment]
Closing this one in favor of #20 - I have an alpha quality multi-threaded runner, soon available via private gem hosting.
