### ISSUE TITLE
Transforming a complete DB

### ISSUE THREAD

**Issue by chuhn** [thbar/kiba#23]
Hi,

in my ETL script I try to do something like this:

``` ruby
%w[table1 table2 table3].each do |t|
  source Source,'db', t
  case t
    when 'table1'
      transform { ... }
  end
  destination Destination,'db2', t
end
```

It looks like that is not how it's supposed to work. Do I have to define seperate ETL jobs for each table?

Chreers,
    Christopher

**Comment by thbar** [comment]
In that specific case, yes, it's better to handle this via separate jobs (one per table), or one parameterized job (like you would pass the table name via an ENV var). Hope this helps!
