### ISSUE TITLE
Error handling, logging, and alerting?

### ISSUE THREAD

**Issue by timuckun** [thbar/kiba#28]
You should add other blocks like ensure, on_error, and flags such as stop_on_error, log etc

Sometimes it's OK to skip one bad row and let the rest of the file process other times not so much.  Also most of the ETL tends to be run unattended to there should be hooks for email alerts or sending data to a monitor.

Thanks.

**Comment by thbar** [comment]
Thanks for your input! Quick reply (but I'll elaborate): skipping one bad row is already possible with a bit of care, and setting up logging & alerting is also doable (I'm doing this in production on a number of deployments).

I'll prepare readme sections for this and will update this ticket once it's ready. Thanks!

**Comment by thbar** [comment]
(to clarify, just in case: most of my ETL deployments run unattended, indeed, and with error handling / logging enabled).

**Comment by jamesohare84** [comment]
Hi @thbar 

That would be an excellent addition. We are currently looking at adding error_handling and logging as part of our implementation.

Look forward to the update

**Comment by thbar** [comment]
@jamesohare84 thanks for the note - I'll try to deliver an article not too late :smile:

**Comment by thbar** [comment]
Please track issue #29 - I'm going to ship a cookbook with more concrete advice on these topics.

**Comment by thbar** [comment]
Follow-up: I've started sharing commonly used helpers (including the one I use for logging on production setup) in the new [kiba-common](https://github.com/thbar/kiba-common) gem.

I'll share back more useful bits over the coming months (either in `kiba-common` or as wiki pages).

**Comment by thbar** [comment]
Closing for now - I will craft an article / kb at some point with more details about this.
