### ISSUE TITLE
1st attempt at a nice solution for progress bars

### ISSUE THREAD

**Issue by technogeeky** [thbar/kiba#30]
So I've started using kiba for some good ETL work, and I wrote a solution that inserts progress bars pretty easily without much fuss. I'm not sure if this is the best way to implement this, but it works.

And now, an example ETL. This is where **all** the ugliness is. It all revolves around the fact that one wants to know the total number of records (so that we can count them), but putting this code in `initialize` isn't enough: that doesn't actually get called in the correct order. So I do this hack where I get **total** out of the file independently, and then keep passing it around.

**etl/customers-to-contacts.etl**

```
#!/usr/bin/env ruby

require 'pry'

require_relative 'SourceCustomers'
require_relative 'DestinationContacts'
require_relative 'Transformations'


source_file = 'C:\\NetClipDev\\CLIPv\\MAINDBF\\customer.dbf'

@progressbar = ProgressBar.create(      title: "#{self.class.name}",
                                        total: SourceCustomers.count(source_file),
                                        autofinish: false
                                        )



pre_process do
   @progressbar.log '[PRE]'
end


source SourceCustomers, source_file, progresses_with: @progressbar, total: SourceCustomers.count(source_file)


transform SkipBadCustomers, '', progresses_with: @progressbar, total: SourceCustomers.count(source_file)


destination DestinationContacts, ''


post_process do
   @progressbar.log '[POST]'
end
```

**SourceCustomers.rb**

```
require 'dbf'
require 'pry'
require_relative './dbfutil'
require_relative './Progressive'

class SourceCustomers
   prepend Progressive
   @total = 0

   def initialize(input_file, options)
      @table ||= DBF::Table.new(input_file)
      @ignored << 'NOTES'
   end

   def self.count(handle)
      @table ||= DBF::Table.new(handle)
      @total = @table.record_count
   end

   def each
     @table.each do |row|
         progress!
         yield(row.attributes_ignoring(@ignored)) unless row.nil?
     end
     @table.close; stop!
   end 
end
```

**Transformations.rb**

```
class SkipBadCustomers
   prepend Progressive

   def initialize(handle, options)
   end

   def process(row)
      row[:num] == -1 ? nil : row 
   end
end
```

And last, the module. Note that you don't have to change **anything** to get started:

**Progressive.rb**

```
module Progressive
   def initialize(handle, options = {})
        @handle = handle
        @options = options
        @pb = @options[:progresses_with]
        @total = @options[:total]
        @format = '%t: |%B| %c/%C'
        @title  = "#{self.class.name}"
        @pb.reset
        super
   end

   def each
       @pb.format   = @format
       @pb.title    = @title
       @pb.progress = 0
       @pb.total    = self.class.count(@handle)
       super
   end

   def process(row)
       if (!@pb.nil? && @pb.progress == @pb.total)
           stop!
           @pb.reset
           @pb.progress = 0
           @pb.format = @format
           @pb.title = @title
           @pb.total = @total
        end
        progress!
        super
   end

   def progress!
       @pb.increment unless (@pb.nil? || @pb.progress == @pb.total)
   end

   def stop!
        puts ''
   end
end
```

So, in this case I am applying the `prepend Progressive` to both a source and a transform class. This creates weird behavior though, namely: You have to wait twice as long overall, because you have to watch the progress bar go through both classes. If you remove this, it takes the expected amount of time, and you never see the SkipBadCustomers bar.

So in this case, you get something like:

```
$ bundle exec kiba etl/customers-to-contacts.etl
[PRE]
SourceCustomers: |================================================ | 14838/14842
SkipBadCustomers: |=============================================== | 14827/14842
[POST]
```

Again, this is rather inefficient. I think there's some funny stuff going on when I do this with the transform. I really wanted it to skip the few bad customers that are there (there should be ~ 10 of these records), and go really fast.

Note there is a bug that's hidden here. If you try to include the elapsed time or the ETA in the format string, it crashes ruby-progressbar. I don't know why, it seemed to be caused by ruby-progressbar's dependence on activerecord or activesupport for time.

Anyway, I'm sure there is room for improvement. Let me know what you think.

**Comment by thbar** [comment]
Hey @technogeeky - thanks for the input! I'll mull over this and let you know what I think indeed.

**Comment by thbar** [comment]
Closing for now - I need to write down an article about that, because there are many different ways to achieve this.
