### ISSUE TITLE
Multiple Transformations 

### ISSUE THREAD

**Issue by attahkhan016** [thbar/kiba#33]
Hello Sir ,
I am trying to have multiple transformations and load to multiple destinations in parallel  , for example 
step I : transform the sample_movies.csv  to a better_movies.csv file with the average rating 
step II : again transform the better_movies.csv to an rated_movies.csv which has higher rating than 8 .
when i try this login , my both the destination.csv files are getting the same output ? 
can you guide ,how to rectify this problem .
please refer the below link for the config files. : 
http://pastebin.com/NbgRDmTW

**Comment by thbar** [comment]
Hello! As mentioned in #32 and in the README, please do not use github issues for these questions but instead use StackOverflow with the `kiba-etl` tag. Thanks!
