### ISSUE TITLE
Passing arguments on the command line

### ISSUE THREAD

**Issue by pmackay** [thbar/kiba#39]
I think this would be useful but dont currently see a way to do it. I'm wrapping Kiba scripts in Rake tasks for convenience and to be able to do other actions. So the paths to input/output file locations are in Rakefiles and duplicated in ETL files. Passing in from the command line would be handy.

**Comment by thbar** [comment]
If you are mostly relying on command line, I can recommend passing ENV variables (as described in [this StackOverflow answer](http://stackoverflow.com/questions/32959692/how-to-pass-parameters-into-your-etl-job).

Still on the command line, if you have more elaborated needs, you can pass an ENV variable giving a path to a YML/JSON file with more configuration.

**Comment by thbar** [comment]
@pmackay I've also added a link to that question in the readme, since it seems like a FAQ. Thanks for asking, let me know if you have further questions!

**Comment by pmackay** [comment]
Very helpful, thanks! It might be worth adding a small note in the `How do you run your ETL jobs?` section of README pointing to the FAQ as well, as that section is about running jobs. 

Much appreciated :)

**Comment by thbar** [comment]
Good suggestion! I just added it. Thanks for your help improving the onboarding experience :smile:

**Comment by thbar** [comment]
FYI @pmackay in addition, Kiba v2 is now out (https://github.com/thbar/kiba/releases/tag/v2.0.0) and officially supports a programmatic invocation. This means that you can implement your own form of CLI very easily, pass more elaborate data (live instance etc).
