### ISSUE TITLE
Allow block-form for source

### ISSUE THREAD

**Issue by thbar** [thbar/kiba#8]
I find myself wrapping sources like this:

``` ruby
require 'oj'

class JSONSource
  def initialize(file)
    @file = file
  end

  def each
    File.open(@file) do |file|
      Oj.load(file).each do |row|
        yield row
      end
    end
  end
end
```

where I'd prefer to be able to write this (at least for one-off scripts):

``` ruby
source do
  File.open(source_file) do |file|
    Oj.load(file).each do |row|
      yield row
    end
  end
end
```

Here the semantic would be that the block must yield each row. Another possible semantic would be this:

``` ruby
source { Oj.load(IO.read(source_file)) }
```

where the block is expected to return something that would respond to `.each`.

Maybe both semantics would be nice to have, with maybe a different keyword or some kind of parameter.

I must think with more depth about this for now, just dropping a note.

**Comment by eduardodeoh** [comment]
:+1:

**Comment by thbar** [comment]
The `yield` construct is afaik not possible to achieve (see [discussion](https://twitter.com/thibaut_barrere/status/613090557221556224)). Passing a block as a param should work though. That, or using enumerables/enumerators.

**Comment by Radagaisus** [comment]
A magic `process` method can do the trick.

``` ruby
source do
  File.open(source_file) do |file|
    Oj.load(file).each do |row|
      process row
    end
  end
end
```

**Comment by thbar** [comment]
@Radagaisus good point - I'll try that out when I look more closely at this again. Thanks!

**Comment by thbar** [comment]
While this seems a "nice to have" idea, in months of production use of Kiba, I never truly felt the actual need to have that. I always end up writing sources as real classes, without feeling any urge to do differently. Closing for now, I'll re-open if I change my mind!
