### ISSUE TITLE
Add shortcut for field transform

### ISSUE THREAD

**Issue by thbar** [thbar/kiba#9]
It's common to just transform one field like this:

``` ruby
transform do |r|
  r[:bought_for] = r[:bought_for].scan(/\[([^\]]+)\]/).flatten
  r
end
```

It could be written shorter like this:

``` ruby
# n = name, v = value, r = row like in aw-etl
field(:bought_for) { |n,v,r| v.scan(/\[([^\]]+)\]/).flatten }
```

I'm not sure if I should pick `field` or `field_transform`, yet.

**Comment by eduardodeoh** [comment]
:+1:  for field_transform

**Comment by thbar** [comment]
Since it's easy to add for anyone via a simple DSL extension, I'll close this for now. I will likely bundle common DSL extensions in Kiba Pro or Kiba at some point though.
